// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quuoyrxahgcoxymjtnsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dW95cnhhaGdjb3h5bWp0bnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDAyMTIsImV4cCI6MjA2MjcxNjIxMn0.K5w0rJVzHNQqWAob2YswBf68KiOezju-lVQjdFbpe_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);